version: '3.8' # Version mise à jour

services:
  testdb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: lune
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: roottest
    networks:
      - localnet
    volumes:
      - databd:/var/lib/mysql

  app_one:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html 
      - ./host:/etc/apache2/sites-enabled
    ports:
      - 8082:80
    depends_on:
      - testdb
    networks:
      - localnet
  
  app_two:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html 
      - ./host:/etc/apache2/sites-enabled
    ports:
      - 8082:80
    depends_on:
      - testdb
    networks:
      - localnet

networks:
  localnet:

volumes:
  databd:
